### ISSUE TITLE
EPIC: Deprecating, removing and making functionalities optional features

### ISSUE THREAD

**Issue by milenkovicm** [apache/datafusion-ballista#1067]
As per our discussion in #1066 I'm opening this epic to break down PR #1066 to set of smaller chunks. 

- [x] #1069 - datafusion python is the main effort, we should focus making it run on ballista
- [x] #1071- this can be contrib project
- [x] #1074 - ci works without it, could not relate content to anything in the repo
- [x] #1070 - never finalized, dangling code
- [x] #1076- this can be a contrib project, we could cover it with pluggable scheduler strategies
- [x] #1073 - library too old, there are newer library to be used
- [x] #1072 - can be a contrib project
- [x] #1079 
- [x] #1084
- [x] #1077 -  only memory store remains, we may want to take different approach, like checkpointing or similar
- [x] #1078 
- [x] #1075 
- [x] #1080
- [x] #1085
- [x] #1109
- [x] #1089
- [x] #1103 & #1102 
- [x] #1114
- [x] #1104 
- [x] #1105
- [x]  #1110
- [x] #1119  (depends on: #1091, #1100, and previous)

For `could be contrib` functionalities I suggest just to remove them at this point, who ever needs them can make contrib project from them

**Comment by milenkovicm** [comment]
@andygrove the other few PR will be pushed once we finish with current backlog, they may introduce merge conflicts
