### ISSUE TITLE
[EPIC]: Ballista Reloaded, Roadmap Proposal

### ISSUE THREAD

**Issue by milenkovicm** [apache/datafusion-ballista#1068]
# Ballista Reloaded - Roadmap Proposal

[As it looks like we reached some kind of  consensus](https://github.com/apache/datafusion-ballista/pull/1066) about moving Ballista from application to a library, I'd like to propose few targets that I see as short to medium term goals for ballista. This would address comments from @alamb & @Dandandan.

Personally, I see two main short term goals, improving ballista usability, and decreasing maintainable code. Robustness may come up as one important goal, for which I don't see bandwidth or infrastructure at this point.

## 0. Keep up with DataFusion releases

Nothing else to add :)

- [x] #1124
- [x] #1153
- [x] #1176
- [x] #1201 

## 1. Usability

It would be great if we could make writing ballista application as easy as DataFusion, ideally it should be very hard to spot the difference between them.

### 1.1 `BallistaContext` removal or evolution

Can we replace `BallistaContext` with `SessionContext`? It would definitely improve usability as we would get most of the methods available in `SessionContext` also, some DataFusion applications would be deployable to Ballista with single line change.

```rust
let ctx = SessionContext::ballista_standalone().await?;
```

This approach may bring DataFusion Python on board as well, not sure how easy would it be.

There are clear benefits of deprecation of `BallistaContext`, decision may hurt us in a long rung.

`SessionContext` may bring usability issues with `UDF` support, configuration and basically all functionalities which need to be propagated across the cluster to work, and which may not be trivial to address. We may try to be address the by "turning off" those methods in ballista or just by documenting it, still some effort is needed. Or maybe its not issue at all?

- [x] #1081
- [x] #1091
- [x] #1099
- [x] #1096
- [x] #1105 

### 1.2 Scheduler/executor binaries

Ballista to a library should keep scheduler and executors binaries, as they would improve overall ballista usability and provide a quick way to bootstrap ballista cluster, for easy on boarding and testing purposes.

We should focus our effort would be to provide a methods which would would help making custom scheduler/executors binaries easy. We could provide a way to create new scheduler/executor with default configurations, or add a way to plug in  object store registries, configurations, protocols, session context factories  ...

- [x] #1115 
- [x] #1098  
- [x] #613 
- [x]  #1227

### 1.3 Ballista Contrib

Move some of the components which are now optional to a separate sub-projects.

## 2. Protocol (client - scheduler - executor)

Two protocols we may need to have a look at, client-scheduler and scheduler-executor.
Two major use cases may be support for user defined functions, configuration propagation and replacement of protocol itself.

- [x] #1170 

### 2.1 Propagate SessionContext configuration from client to executor

At the moment SessionContext or some other state is not propagated from client to scheduler and executors.
Enabling this would simplify overall configuration, it would enable use-cases where configuration can hold
secret keys, object store configuration or similar.

- [x] configuration cleanup #1108
- [x] update client side (propagate `SessionConfig` when `scheduler_client.create_session` called) #1108
- [x] update scheduler side, make session config first class citizen #1108

### 2.2 Support for user defined functions

I'm not aware of any examples where rust based UDFs are made serializable and shipped from client to server,
many examples where python functions are shipped, so this effort may focus on python UDF. This effort
would probably impact DataFusion plans, more details to follow.

### 2.3 Make client-scheduler protocol plugable

Current client-scheduler protocol will be improved, also as there are new protocols coming out we may provide
a way to replace default protocol.

One (new) protocol example is [Spark Connect](https://spark.apache.org/docs/latest/spark-connect-overview.html), it is well thought approach covering most if not all cases for layered data processing. Users could be able to provide support for it and deploy frameworks like [Sail](https://github.com/lakehq/sail) on top of Ballista or even spark applications. Personally I find this interesting and with growing operators from DataFusion Comet supports it might bring interesting possibilities.

Also, this is needed if flight-sql is made optional and moved to 'contrib' project.

### 2.4 Bridge the gap between datafusion and ballista 

Some operations are supported by datafusion but not ballista, we should try to bridge the gap 

- [x] https://github.com/apache/datafusion/issues/13616
- [x] #1164

## 3. Shuffle improvements

@andygrove mentioned, [re-implement the shuffle writer/reader to re-use the logic in Comet which has a more efficient shuffle implementation based on Spark](https://discord.com/channels/885562378132000778/1179822705525141605/1277287101800386713). It would be great if we could see this implemented in short term.

## 4. Scheduler

Improvements to internal scheduler could be a mid to long term goal, where users can bring their own strategies. Not many use-cases come to my mind apart from HDFS collocation or caching.

Two possible items here:

- #1238 
- Adding/improving Failure detector(s)

## 5. Observability

As UI has been removed, and rest-api may be moved to contrib API we need to come up with notification mechanism external systems can subscribe to get scheduling events, execution metrics ... We would need to put some more effort to break down this functionality. I guess we could learn from Apache Spark

## 6. Testing

Effort into getting more tests and covering edge cases. It may not be easy as it needs additional infrastructure and lot of effort for testing. It would be great if we can re-use DataFusion set of tests somehow 

## 7. Python bindings

Make ballista available for `datafusion-python` users

- [x] #1100
- [ ] #1142 
- [x] #1132
- [ ] #1120
- [x] #1107

**Comment by drauschenbach** [comment]
Re: 2.2 User Defined Functions:

Rust compiles to WASM, and WASM explicitly supports over-the-air deployment. This is one possible way to express UDF's in Rust.

Some other projects allow UDFs in "pickle-able Python", although use of transitive dependencies rapidly descends into Python packaging hell.

**Comment by wpf375516041** [comment]
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/a4db45c0-ee7f-48e0-aa61-49782019212a">
Does starrocks java udf have any reference value?

**Comment by tbar4** [comment]
I think pictures and graphs help me better understand what is being updated, so I made this to reflect what I think you are saying should be updated. I am happy to update and create a proposed Architecture that we can maybe put on the site. 
![ballista drawio](https://github.com/user-attachments/assets/0a6c00d0-3860-4900-b383-1565b7d2f3a1)

**Comment by milenkovicm** [comment]
>  Does starrocks java udf have any reference value?

@wpf375516041 its not too hard to implement java udf on top of datafusion. I did example implementation some time ago https://github.com/milenkovicm/adhesive

**Comment by milenkovicm** [comment]
After epic 6 months, I'm closing this issue. I would propose to have further discussion about ballista in #1245

Thank you everyone for your help, support and contribution over the last while.
