### ISSUE TITLE
Update Documentation with `SessionContextExt`

### ISSUE THREAD

**Issue by milenkovicm** [apache/datafusion-ballista#1105]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

With introduction of `SessionContextExt` we would been to update documentation to reflect the change

**Describe the solution you'd like**

- [ ] update quick start and rust guides at, once we get #1102, #1103 in and from changelogs in #1096 , #1088 <https://datafusion.apache.org/ballista/user-guide/deployment/quick-start.html> <https://datafusion.apache.org/ballista/user-guide/rust.html>
- [ ] update configuration options once we get #1104 <https://datafusion.apache.org/ballista/user-guide/configs.html>
- [ ] update python: <https://datafusion.apache.org/ballista/user-guide/python.html> once we get #1091 #1100 merged

**Describe alternatives you've considered**

**Additional context**

It would be great if we could get `README.MD` trimmed a bit, with example how to setup and make DataFusion distributed at the very top of the readme.

**Comment by tbar4** [comment]
@milenkovicm can you assign this to me? I just spent more time than I would like using [this](https://datafusion.apache.org/ballista/user-guide/rust.html) documentation as the basis for #1100 instead of the new updated SessionState in [SessionState](https://github.com/apache/datafusion/blob/382ba2b1605d244a10db21f4527e11570caa4323/datafusion/core/src/execution/session_state.rs)

**Comment by milenkovicm** [comment]
@tbar4  i have started drafting changes in https://github.com/milenkovicm/arrow-ballista/tree/doc_update_root_readme i did not push it for review yet as #1108 not merged. lets get that merged first and once we start removing ballista context we could update docs ... btw I have no right to assign tasks to anyone ... just put your name in comment and thats it i believe
